<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_IntegrationEdit</name>
   <tag></tag>
   <elementGuidId>73338336-f44f-4846-88db-e940334f430d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//td/span[contains(text(),'Automation')]/../../td[7]/div</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
