<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_IntegrationStatus</name>
   <tag></tag>
   <elementGuidId>509473a3-ec90-4150-b797-2187241fa87f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//td/span[contains(text(),'Automation')]/../../td[6]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
