<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_Signin</name>
   <tag></tag>
   <elementGuidId>71dffcc0-9487-4a38-a94c-ad6b2c1c35a1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@class='modal-body']/div[2]/div[3]/div/div/form/input[3]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@name = 'signInSubmitButton']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btn-login</value>
      <webElementGuid>465c8af0-d8fb-422f-b752-73b95d8d2be7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>signInSubmitButton</value>
      <webElementGuid>f431e03d-0fe9-419c-a1bb-25d39385b670</webElementGuid>
   </webElementProperties>
</WebElementEntity>
