<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Arney Bilbery</name>
   <tag></tag>
   <elementGuidId>c9d97fa3-33d2-45b7-869b-c443af611a34</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.suggestions-list.css-0 > ul > li:nth-of-type(2)</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//body[@id='root']/div[5]/div/ul/li[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=option[name=&quot;Arney Bilbery&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>fe1cbb8d-5ea4-4958-ab29-fbffa09a81db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>365a2b6f-38ca-4ceb-afcd-15807aecc19b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>ad269bd9-997c-45ef-87ba-a99f234b4fc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Arney Bilbery</value>
      <webElementGuid>469dec1a-c5e2-4f9f-babe-54a2539d4f1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;chakra-portal&quot;]/div[@class=&quot;suggestions-list css-0&quot;]/ul[1]/li[2]</value>
      <webElementGuid>33490690-e8a5-492d-b3d4-e03a2079b4ff</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='root']/div[5]/div/ul/li[2]</value>
      <webElementGuid>4bc0b307-0276-4658-a992-e72e11b2b7ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ailey Pakeman'])[2]/following::li[1]</value>
      <webElementGuid>480dac65-389b-45fb-9a47-cd3d5b3c2709</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Delete'])[2]/following::li[5]</value>
      <webElementGuid>7b42e10b-754d-4dff-92f1-49b2f44d091e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Charil Hambright'])[1]/preceding::li[1]</value>
      <webElementGuid>e6752e15-6bfc-4cfd-89fc-f5f36814c085</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Deeyn Gobbet'])[1]/preceding::li[2]</value>
      <webElementGuid>57d71b8e-5043-49f3-aac6-6f19512404c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Arney Bilbery']/parent::*</value>
      <webElementGuid>f8d68a12-c788-4a37-955a-a8dab568ec40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/ul/li[2]</value>
      <webElementGuid>baf82f76-98cb-4004-bda0-3af99fbf04a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'Arney Bilbery' or . = 'Arney Bilbery')]</value>
      <webElementGuid>4cf39a17-1b00-43f4-8ace-e2ce77957792</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
