<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_ALL</name>
   <tag></tag>
   <elementGuidId>1f80a345-f710-4f3b-bc3c-a9c31afd8632</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.suggestions-list.css-0 > ul > li:nth-of-type(3)</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//body[@id='root']/div[5]/div/ul/li[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=option[name=&quot;ALL&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>29dc3cdf-d467-4e46-99a6-eb59fee64973</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>6a818475-4bb1-4e17-9ec7-3cb804c2fcc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>786568ab-fc15-4c15-8d07-d85f9c0e3429</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ALL</value>
      <webElementGuid>5edbc58a-624e-44d1-abbc-e3cd5aea4f27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;chakra-portal&quot;]/div[@class=&quot;suggestions-list css-0&quot;]/ul[1]/li[3]</value>
      <webElementGuid>a80db9ee-346b-4483-8fd4-8cd8857fb542</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='root']/div[5]/div/ul/li[3]</value>
      <webElementGuid>467a6739-52b8-4a6e-b244-b9a26bb20783</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='memberOf: Staff'])[1]/following::li[1]</value>
      <webElementGuid>4c909621-6869-404e-8fec-1ea240c39b01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Doctor'])[2]/following::li[2]</value>
      <webElementGuid>e75b6aca-9d9b-44d7-b81e-7191b7889d98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='ALL']/parent::*</value>
      <webElementGuid>8baea954-f23c-4ae4-ab9d-c150bc0ab327</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/ul/li[3]</value>
      <webElementGuid>f748a3cb-22f6-4972-aa1c-0d0124ebbcb4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'ALL' or . = 'ALL')]</value>
      <webElementGuid>81663ef1-49c5-4e3b-9e0c-5a4898a0bad7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
