<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_assignPatient</name>
   <tag></tag>
   <elementGuidId>f3dc9b80-75f1-458e-9e9c-12cb2497893d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.suggestions-list.actions-list.css-0 > ul > li</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//body[@id='root']/div[5]/div/ul/li</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=option[name=&quot;assignPatient&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>fbdfe078-7999-4a5b-a61a-06c6629703cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>f7431936-22db-45e4-abab-56f0b162e011</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>assignPatient</value>
      <webElementGuid>08c978e7-4fab-48a6-827b-26895c93ff4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;chakra-portal&quot;]/div[@class=&quot;suggestions-list actions-list css-0&quot;]/ul[1]/li[1]</value>
      <webElementGuid>a26165ac-19ac-4e48-9ff1-dac672a1b2a6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='root']/div[5]/div/ul/li</value>
      <webElementGuid>98282e3f-ecfc-48dc-be1a-d7a336f286d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Delete'])[1]/following::li[4]</value>
      <webElementGuid>bb8f1ae4-2ca3-47d7-8371-1a863552000d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reset Node'])[2]/following::li[4]</value>
      <webElementGuid>1e141d66-3d26-4e92-abb0-d9766cebb68a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='commentPatientRecord'])[1]/preceding::li[1]</value>
      <webElementGuid>db0d1469-2239-46a6-aa3c-42c18d2cafda</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='dischargePatient'])[1]/preceding::li[2]</value>
      <webElementGuid>27e66573-97ef-4819-9bb1-f4ae07996da8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='assignPatient']/parent::*</value>
      <webElementGuid>a36d27cb-c3e0-4324-aeb5-45e7c1044f4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/ul/li</value>
      <webElementGuid>3a4d258d-503a-44b0-a300-4d159ee832d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'assignPatient' or . = 'assignPatient')]</value>
      <webElementGuid>70c697a4-835a-4d18-8d0a-d6f9233a3d92</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
