<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_dev</name>
   <tag></tag>
   <elementGuidId>a3f21b90-1ff8-4c40-a343-476560ede2f7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>p.chakra-text.css-1awam7r</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//body[@id='root']/div/div/aside/div/div/div/nav/ul/li[2]/a/span[2]/p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>a >> internal:has-text=/^dev$/</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>9a33f86e-ddd5-4ffe-91dc-319bf81f4fb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chakra-text css-1awam7r</value>
      <webElementGuid>c490bfba-956c-47e0-8484-9684fdbae613</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>white-space</name>
      <type>Main</type>
      <value>nowrap</value>
      <webElementGuid>46873d25-1aae-4a45-8512-43b49086fdbd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>dev</value>
      <webElementGuid>b7855446-506e-455b-a97c-f7d8737dde46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;css-k008qs&quot;]/div[@class=&quot;applicationMenu css-1yeiifd&quot;]/aside[@class=&quot;ps-sidebar-root ps-toggled ps-broken css-11i2auh&quot;]/div[@class=&quot;ps-sidebar-container css-1mb249p&quot;]/div[@class=&quot;css-0&quot;]/div[@class=&quot;css-0&quot;]/nav[@class=&quot;ps-menu-root css-vj11vy&quot;]/ul[@class=&quot;css-ewdv3l&quot;]/li[@class=&quot;ps-menuitem-root ps-submenu-root css-16jesut&quot;]/a[@class=&quot;ps-menu-button&quot;]/span[@class=&quot;ps-menu-label css-12w9als&quot;]/p[@class=&quot;chakra-text css-1awam7r&quot;]</value>
      <webElementGuid>ee80389b-5067-4129-afcd-ecc23cdf1c4b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='root']/div/div/aside/div/div/div/nav/ul/li[2]/a/span[2]/p</value>
      <webElementGuid>309d9fd9-d3c2-486a-9a6d-0762564d7d06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Insights'])[1]/following::p[1]</value>
      <webElementGuid>ba5e9493-1c67-4e31-ac64-d7b458b060ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View more'])[1]/preceding::p[14]</value>
      <webElementGuid>087782c9-a2a1-4f16-9aa5-543fc9a2d9c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Know more'])[1]/preceding::p[17]</value>
      <webElementGuid>5ebed6a8-6843-4e55-93be-23751e0860f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='dev']/parent::*</value>
      <webElementGuid>1a145c84-b471-4a8c-9848-6d7050604b71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/p</value>
      <webElementGuid>fc5ddaea-7882-41f5-9215-62b224136260</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'dev' or . = 'dev')]</value>
      <webElementGuid>7e3fdc83-adf0-4efd-b619-fb94717f5381</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
