<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_assignPatient</name>
   <tag></tag>
   <elementGuidId>9238dc66-7a05-4794-aed4-ceb6e6dd02dd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div:nth-of-type(3) > pre.CodeMirror-line > span > span.cm-entityvalue-keyword</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='editorlayout']/div/div[6]/div/div/div/div/div[5]/div[3]/pre/span/span[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;\&quot;assignPatient\&quot;&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>302c513c-4e47-4060-be39-4ea8f73265a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cm-entityvalue-keyword</value>
      <webElementGuid>2805d34f-7137-4f85-bcf8-54502ba9f588</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>&quot;assignPatient&quot;</value>
      <webElementGuid>7b5f39fc-4efb-4a52-8387-7aa10125573a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;editorlayout&quot;)/div[@class=&quot;CodeMirror cm-s-xq-light CodeMirror-wrap CodeMirror-focused&quot;]/div[@class=&quot;CodeMirror-scroll&quot;]/div[@class=&quot;CodeMirror-sizer&quot;]/div[1]/div[@class=&quot;CodeMirror-lines&quot;]/div[1]/div[@class=&quot;CodeMirror-code&quot;]/div[3]/pre[@class=&quot;CodeMirror-line&quot;]/span[1]/span[@class=&quot;cm-entityvalue-keyword&quot;]</value>
      <webElementGuid>afc433a0-96f7-4da4-b566-cc24a26ff3b0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='editorlayout']/div/div[6]/div/div/div/div/div[5]/div[3]/pre/span/span[4]</value>
      <webElementGuid>7a6f1e0d-9374-4bb5-ba58-643cea41436c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='RevaHospital::Action::'])[1]/following::span[1]</value>
      <webElementGuid>ef86231e-fc21-4f17-aacf-6d223e19dedb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='=='])[2]/following::span[2]</value>
      <webElementGuid>acc51634-c15e-44f1-8831-2eb46133842e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=','])[2]/preceding::span[1]</value>
      <webElementGuid>7a2662e2-f405-4a72-a33c-d38919516f35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='resource'])[1]/preceding::span[2]</value>
      <webElementGuid>dda2a5d0-4d96-463e-91a3-b1d7e3d13e60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='&quot;assignPatient&quot;']/parent::*</value>
      <webElementGuid>c61352ed-0948-4fb3-ae01-1fde3e19d7cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/pre/span/span[4]</value>
      <webElementGuid>46164894-477d-4ef5-8dd5-1a7ff1accabf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '&quot;assignPatient&quot;' or . = '&quot;assignPatient&quot;')]</value>
      <webElementGuid>74bb318b-2bff-4e96-b9fa-d8dd8afe955f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
