<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Medication</name>
   <tag></tag>
   <elementGuidId>423f9e0d-4836-4883-8a3f-3e2a40fed19a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='chakra-modal--body-:r2hv:']/div/div[2]/div/div/div/div[2]/div/div/div[2]/div/div[9]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>div >> internal:has-text=/^Medication$/</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>8d6c66bd-19a9-4b55-821b-621f24fd519f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-190h1nq</value>
      <webElementGuid>cf138ba9-eee1-4400-b784-8451371df5cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Medication</value>
      <webElementGuid>bbec1645-1503-466a-9984-a50a90b1b828</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;chakra-modal--body-:r2hv:&quot;)/div[@class=&quot;css-j7qwjs&quot;]/div[@class=&quot;css-0&quot;]/div[@class=&quot;css-10klw3m&quot;]/div[@class=&quot;css-j7qwjs&quot;]/div[@class=&quot;css-10nql6b&quot;]/div[@class=&quot;css-1aeraip&quot;]/div[@class=&quot;css-10klw3m&quot;]/div[@class=&quot;css-mfcpbk&quot;]/div[@class=&quot;css-18n7w4c&quot;]/div[@class=&quot;css-0&quot;]/div[@class=&quot;css-190h1nq&quot;]</value>
      <webElementGuid>b0616afc-6ee7-44a7-a7c1-2cf4bedb1d43</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='chakra-modal--body-:r2hv:']/div/div[2]/div/div/div/div[2]/div/div/div[2]/div/div[9]</value>
      <webElementGuid>fb20fa57-c09a-4fd2-98d0-104492c83149</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TestEnv One'])[2]/following::div[24]</value>
      <webElementGuid>39c62fc2-3cea-4130-a492-339657df63b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Next'])[1]/following::div[32]</value>
      <webElementGuid>3c25a00e-5c5c-4c19-ab2a-cf954f35b237</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Attribute Type'])[2]/preceding::div[18]</value>
      <webElementGuid>012e35e2-ab59-49d5-9b8d-76337d1e171e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Boolean'])[1]/preceding::div[18]</value>
      <webElementGuid>7bfdc424-ed5a-4133-b4a0-fd9735a5e45d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]</value>
      <webElementGuid>b2cabacd-879c-4134-b03e-e468b4b40409</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Medication' or . = 'Medication')]</value>
      <webElementGuid>434730cc-18a0-4635-8383-3d17b6ceb707</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
