<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Nurse</name>
   <tag></tag>
   <elementGuidId>f2965fd9-e07c-4308-ae25-f3082e3532bc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='chakra-modal--body-:r2hv:']/div/div[2]/div/div/div/div[2]/div/div/div[2]/div/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.css-190h1nq</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>div >> internal:has-text=/^Nurse$/</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>c4efbb77-af15-46fc-951b-879a92bb8593</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-190h1nq</value>
      <webElementGuid>e82226dd-5e71-49b9-a099-82fbe6ac6bb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Nurse</value>
      <webElementGuid>c8be52ea-0c0c-4ddd-9953-6763ee26d844</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;chakra-modal--body-:r2hv:&quot;)/div[@class=&quot;css-j7qwjs&quot;]/div[@class=&quot;css-0&quot;]/div[@class=&quot;css-10klw3m&quot;]/div[@class=&quot;css-j7qwjs&quot;]/div[@class=&quot;css-10nql6b&quot;]/div[@class=&quot;css-1aeraip&quot;]/div[@class=&quot;css-10klw3m&quot;]/div[@class=&quot;css-mfcpbk&quot;]/div[@class=&quot;css-18n7w4c&quot;]/div[@class=&quot;css-0&quot;]/div[@class=&quot;css-190h1nq&quot;]</value>
      <webElementGuid>50ae68eb-3597-436f-8141-c875b097539c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='chakra-modal--body-:r2hv:']/div/div[2]/div/div/div/div[2]/div/div/div[2]/div/div[2]</value>
      <webElementGuid>f9750701-18cd-4682-af0b-59cad10886fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TestEnv One'])[2]/following::div[10]</value>
      <webElementGuid>9a1d14a3-b455-4f3a-bf7c-7b0e8e62cee5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Next'])[1]/following::div[18]</value>
      <webElementGuid>6ac42240-8a65-4b7b-b69b-4c6aad0ce7ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Attribute Type'])[2]/preceding::div[32]</value>
      <webElementGuid>2ad39b6e-bd8e-45dd-b957-02a3c1e7353d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Boolean'])[1]/preceding::div[32]</value>
      <webElementGuid>ebb5b18a-4ad4-4287-9068-3bcbe4566603</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/div/div[2]</value>
      <webElementGuid>7f9c6d54-e075-4ee3-a0de-3e89fd47b1b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Nurse' or . = 'Nurse')]</value>
      <webElementGuid>b003241d-3185-40e6-a214-3fb9aaa48de1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
