<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Patient</name>
   <tag></tag>
   <elementGuidId>cbc1b880-cc40-47f4-9f66-4d899514e709</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='chakra-modal--body-:r2hv:']/div/div[2]/div/div/div/div[2]/div/div/div[2]/div/div[4]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>div >> internal:has-text=/^Patient$/</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>62b84572-c861-45a2-9fef-13853ca162a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-190h1nq</value>
      <webElementGuid>dcf9219a-2fc9-4f43-b582-02234c7aeaf7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Patient</value>
      <webElementGuid>05415637-54d5-4535-adff-f5b1e36285ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;chakra-modal--body-:r2hv:&quot;)/div[@class=&quot;css-j7qwjs&quot;]/div[@class=&quot;css-0&quot;]/div[@class=&quot;css-10klw3m&quot;]/div[@class=&quot;css-j7qwjs&quot;]/div[@class=&quot;css-10nql6b&quot;]/div[@class=&quot;css-1aeraip&quot;]/div[@class=&quot;css-10klw3m&quot;]/div[@class=&quot;css-mfcpbk&quot;]/div[@class=&quot;css-18n7w4c&quot;]/div[@class=&quot;css-0&quot;]/div[@class=&quot;css-190h1nq&quot;]</value>
      <webElementGuid>55991134-e677-4363-8260-316171b0b85a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='chakra-modal--body-:r2hv:']/div/div[2]/div/div/div/div[2]/div/div/div[2]/div/div[4]</value>
      <webElementGuid>863197b8-a10f-473d-afa6-4b7bedace005</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TestEnv One'])[2]/following::div[14]</value>
      <webElementGuid>13ffaf98-fc0c-4959-afa7-2168f4e97983</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Next'])[1]/following::div[22]</value>
      <webElementGuid>661dad0a-7c56-45da-8b07-98d8f5037783</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Attribute Type'])[2]/preceding::div[28]</value>
      <webElementGuid>adc73291-56c4-4da4-98b3-0a53b7b21ae7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Boolean'])[1]/preceding::div[28]</value>
      <webElementGuid>6b24dc9e-f910-4f32-97d9-3b8e33a35936</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/div/div[4]</value>
      <webElementGuid>1edacdc6-9e6e-451e-b7d9-5e08c62d2fe5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Patient' or . = 'Patient')]</value>
      <webElementGuid>f68f4df9-0878-449e-9b7e-6c18de6ed11e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
