<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_261741375814</name>
   <tag></tag>
   <elementGuidId>db9742dd-910b-428b-8558-329e1ab34e32</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='chakra-modal--body-:r67:']/div/div/div[4]/div[2]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.css-xxblwg</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Create Policy Store&quot;i >> internal:text=&quot;261741375814&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>43766ec1-089c-4f09-b159-2bebe68e823f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-xxblwg</value>
      <webElementGuid>02daf908-0a29-492c-a5f1-ba3fc2a7f31c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>261741375814</value>
      <webElementGuid>92e16667-b10a-4b84-ae8a-08d0295c24d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;chakra-modal--body-:r67:&quot;)/div[@class=&quot;css-7pdtuu&quot;]/div[@class=&quot;css-11mk2k7&quot;]/div[@class=&quot;css-0&quot;]/div[@class=&quot;css-oss6ys&quot;]/div[@class=&quot;css-xxblwg&quot;]</value>
      <webElementGuid>6fb1311e-5a8d-423e-981a-ba938df4863a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='chakra-modal--body-:r67:']/div/div/div[4]/div[2]/div</value>
      <webElementGuid>f3cb7f68-9d8b-4b88-8168-b806bcf90705</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='us-east-2-261741375814-DO-NOT-DELETE'])[1]/following::div[5]</value>
      <webElementGuid>f140e7db-8ccd-4643-aff0-ae14a5551cb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[4]/following::div[9]</value>
      <webElementGuid>c16600bb-1ffb-4ffd-9801-ae776d5c1b5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='us-east-2'])[2]/preceding::div[1]</value>
      <webElementGuid>40b8c35d-bd33-4700-8a55-f1c57b668ab5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/preceding::div[2]</value>
      <webElementGuid>ce067df3-7a7f-498f-aee2-7799d2365ab9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/div</value>
      <webElementGuid>ca7c85e1-b581-48f0-a01c-9efec06bb31c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '261741375814' or . = '261741375814')]</value>
      <webElementGuid>1561da1f-1890-4537-bc26-43feb08a28d7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
