<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_text_1_2_3_4_5_6_7_8_9_10</name>
   <tag></tag>
   <elementGuidId>0ec5bea4-1da7-45f2-b271-cf1566bb14fc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='C']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.react-flow__node.react-flow__node-custom.selected.selectable > div.node-container.react-flow-entityType.css-0 > div.css-ezw9vm > div.schemabuilder.inputWrapper.css-se2h9a > div.css-95g4uk > div.css-1xuzov8 > div.autocomplete-container > input[type=&quot;text&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-testid=&quot;rf__node-NnKiW0w6SrcF3fRsp3mMg&quot;] >> internal:attr=[placeholder=&quot;Type here&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>62eab227-0a84-40a8-9838-4f9022645b2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Type here</value>
      <webElementGuid>66ccdf14-1018-423e-99ce-3d4144f2f87b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c403b703-1d25-4e43-8c65-eacd6ea2fee7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>C</value>
      <webElementGuid>65e0ca1d-05dc-4e0b-b555-566e4810fef2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;chakra-modal--body-:r2hv:&quot;)/div[@class=&quot;css-j7qwjs&quot;]/div[@class=&quot;css-0&quot;]/div[@class=&quot;css-0&quot;]/div[@class=&quot;css-3q5yk1&quot;]/div[@class=&quot;css-1g6fs54&quot;]/div[@class=&quot;css-dj8sho&quot;]/div[@class=&quot;react-flow&quot;]/div[@class=&quot;react-flow__renderer&quot;]/div[@class=&quot;react-flow__pane selection&quot;]/div[@class=&quot;react-flow__viewport react-flow__container&quot;]/div[@class=&quot;react-flow__nodes&quot;]/div[@class=&quot;react-flow__node react-flow__node-custom selected selectable&quot;]/div[@class=&quot;node-container react-flow-entityType css-0&quot;]/div[@class=&quot;css-ezw9vm&quot;]/div[@class=&quot;schemabuilder inputWrapper css-se2h9a&quot;]/div[@class=&quot;css-95g4uk&quot;]/div[@class=&quot;css-1xuzov8&quot;]/div[@class=&quot;autocomplete-container&quot;]/input[1]</value>
      <webElementGuid>529977df-b373-45a9-9163-1842d4d6597c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='C']</value>
      <webElementGuid>447d7565-3531-49ea-8092-f45455b11d79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='chakra-modal--body-:r2hv:']/div/div[2]/div/div/div[2]/div[2]/div/div/div/div/div[2]/div[6]/div/div/div[2]/div/div/div/input</value>
      <webElementGuid>52d59d81-4bea-42a6-b6ce-e1552d323edb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/input</value>
      <webElementGuid>4d29d88b-3378-40b8-a949-74abb79be682</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Type here' and @type = 'text']</value>
      <webElementGuid>8e3c5847-5734-48ee-bf2d-4b93d2ff7c70</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
