<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_text_1</name>
   <tag></tag>
   <elementGuidId>4648b524-d869-408f-adf1-ec99d2222d31</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='A']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.autocomplete-container > input[type=&quot;text&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Type here&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1b88e8d6-31c0-4ebe-9286-aa5983dc2cf4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Type here</value>
      <webElementGuid>29a2e2f2-c51a-4df9-ad1e-b36b765d74f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1b7f4e0a-8a82-4fa7-be28-4c54e0e9199b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>A</value>
      <webElementGuid>ae6a270a-5944-4a0e-a9e6-99506444e287</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;chakra-modal--body-:r2hv:&quot;)/div[@class=&quot;css-j7qwjs&quot;]/div[@class=&quot;css-0&quot;]/div[@class=&quot;css-0&quot;]/div[@class=&quot;css-3q5yk1&quot;]/div[@class=&quot;css-1g6fs54&quot;]/div[@class=&quot;css-dj8sho&quot;]/div[@class=&quot;react-flow&quot;]/div[@class=&quot;react-flow__renderer&quot;]/div[@class=&quot;react-flow__pane selection&quot;]/div[@class=&quot;react-flow__viewport react-flow__container&quot;]/div[@class=&quot;react-flow__nodes&quot;]/div[@class=&quot;react-flow__node react-flow__node-custom selected selectable&quot;]/div[@class=&quot;node-container react-flow-entityType css-0&quot;]/div[@class=&quot;css-ezw9vm&quot;]/div[@class=&quot;schemabuilder inputWrapper css-se2h9a&quot;]/div[@class=&quot;css-95g4uk&quot;]/div[@class=&quot;css-1xuzov8&quot;]/div[@class=&quot;autocomplete-container&quot;]/input[1]</value>
      <webElementGuid>35f44ea3-2e9b-4017-b1a9-695fee94276e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='A']</value>
      <webElementGuid>adb050d9-4835-4d5b-aee0-4a1b7ed77675</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='chakra-modal--body-:r2hv:']/div/div[2]/div/div/div[2]/div[2]/div/div/div/div/div[2]/div[4]/div/div/div/div/div/div/input</value>
      <webElementGuid>0de5c2d4-48d2-4726-be11-f03d821e7c43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/div/div/div/input</value>
      <webElementGuid>ac3b9f4c-6a21-4400-99bc-461fafa157c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Type here' and @type = 'text']</value>
      <webElementGuid>6e9f242a-b972-45f5-a3bb-b74e1e3945cf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
