<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_text_1_2_3_4_5_6</name>
   <tag></tag>
   <elementGuidId>1632a193-9f75-4803-a951-33ff23205cea</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='U']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.css-1xuzov8 > input[type=&quot;text&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-testid=&quot;rf__node-skOMegqxtCSymMLPaA3YB&quot;] >> internal:attr=[placeholder=&quot;Type here&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>690a883d-5ae1-425e-a511-2d4ef4b06b9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Type here</value>
      <webElementGuid>48c7e468-d8a0-40ce-9385-87c94d4f4d43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>edfa125a-aa50-4655-9ed4-3b19cad24bf8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>U</value>
      <webElementGuid>bf9105c7-579a-4352-ba17-72ee8ded44d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;chakra-modal--body-:r2hv:&quot;)/div[@class=&quot;css-j7qwjs&quot;]/div[@class=&quot;css-0&quot;]/div[@class=&quot;css-0&quot;]/div[@class=&quot;css-3q5yk1&quot;]/div[@class=&quot;css-1g6fs54&quot;]/div[@class=&quot;css-dj8sho&quot;]/div[@class=&quot;react-flow&quot;]/div[@class=&quot;react-flow__renderer&quot;]/div[@class=&quot;react-flow__pane selection&quot;]/div[@class=&quot;react-flow__viewport react-flow__container&quot;]/div[@class=&quot;react-flow__nodes&quot;]/div[@class=&quot;react-flow__node react-flow__node-custom selected selectable&quot;]/div[@class=&quot;node-container react-flow-entityType css-0&quot;]/div[@class=&quot;css-ezw9vm&quot;]/div[@class=&quot;schemabuilder inputWrapper css-se2h9a&quot;]/div[@class=&quot;css-95g4uk&quot;]/div[@class=&quot;css-1xuzov8&quot;]/input[1]</value>
      <webElementGuid>ca5c51e6-de6d-40c1-950f-81716b6c3665</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='U']</value>
      <webElementGuid>e1d85ed7-aa8f-4286-a2f3-698431e4c24b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='chakra-modal--body-:r2hv:']/div/div[2]/div/div/div[2]/div[2]/div/div/div/div/div[2]/div[5]/div/div/div[2]/div/div/input</value>
      <webElementGuid>a60ee4cc-8c76-4437-9d33-dea497392607</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/input</value>
      <webElementGuid>fdbaa98d-9c07-470b-b575-00f2b8c0c227</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Type here' and @type = 'text']</value>
      <webElementGuid>17ee4ae5-0294-420e-93ab-03f9d0176800</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
