<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_text_1_2_3_4_5_6_7_8_9_10_11_12_13_14_15_16_17</name>
   <tag></tag>
   <elementGuidId>e93a684a-a61f-4a07-afdd-c3be33c1f9ee</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='Customer']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.react-flow__node.react-flow__node-custom.selected.selectable > div.node-container.react-flow-entityType.css-0 > div.css-ezw9vm > div.schemabuilder.inputWrapper.css-se2h9a > div.css-95g4uk > div.css-1xuzov8 > div.autocomplete-container > input[type=&quot;text&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-testid=&quot;rf__node-NnKiW0w6SrcF3fRsp3mMg&quot;] >> internal:attr=[placeholder=&quot;Type here&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c661b799-e20f-4b53-94b0-8fe405585ba8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Type here</value>
      <webElementGuid>a68559ed-ef4c-408c-8f1f-99ad017a3d33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>222d7ac0-558f-489b-9965-3f63bcb1162e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Customer</value>
      <webElementGuid>7661238a-8def-4670-a227-f78ae487f8e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;chakra-modal--body-:r2hv:&quot;)/div[@class=&quot;css-j7qwjs&quot;]/div[@class=&quot;css-0&quot;]/div[@class=&quot;css-0&quot;]/div[@class=&quot;css-3q5yk1&quot;]/div[@class=&quot;css-1g6fs54&quot;]/div[@class=&quot;css-dj8sho&quot;]/div[@class=&quot;react-flow&quot;]/div[@class=&quot;react-flow__renderer&quot;]/div[@class=&quot;react-flow__pane&quot;]/div[@class=&quot;react-flow__viewport react-flow__container&quot;]/div[@class=&quot;react-flow__nodes&quot;]/div[@class=&quot;react-flow__node react-flow__node-custom selected selectable&quot;]/div[@class=&quot;node-container react-flow-entityType css-0&quot;]/div[@class=&quot;css-ezw9vm&quot;]/div[@class=&quot;schemabuilder inputWrapper css-se2h9a&quot;]/div[@class=&quot;css-95g4uk&quot;]/div[@class=&quot;css-1xuzov8&quot;]/div[@class=&quot;autocomplete-container&quot;]/input[1]</value>
      <webElementGuid>710c7bf3-0f69-41b9-99ca-a69d530b299b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='Customer']</value>
      <webElementGuid>1775f0fa-8448-49d0-8807-4715a1f9abe1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='chakra-modal--body-:r2hv:']/div/div[2]/div/div/div[2]/div[2]/div/div/div/div/div[2]/div[6]/div/div/div[2]/div/div/div/input</value>
      <webElementGuid>ac945f0e-4aa4-43d3-a655-a835af90f8fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/input</value>
      <webElementGuid>3f406ca8-5975-4757-addf-2169328ad814</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Type here' and @type = 'text']</value>
      <webElementGuid>1f3b1850-467c-4396-b30b-716e2199fda4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
