<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_text</name>
   <tag></tag>
   <elementGuidId>e7c38d8f-d975-400f-8eb6-521d6fff535d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@value=''])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-testid=&quot;rf__node-NQakM3qlsT_tu1cVT_yFd&quot;] >> internal:attr=[placeholder=&quot;Type here&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a8dd22a7-18a5-4c98-bd53-95ad03e6297c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Type here</value>
      <webElementGuid>dbb08bed-21fc-4598-8169-0f6dba08fdcb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>25b517fe-d8f3-451b-943b-0873a4d61474</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;chakra-modal--body-:r2hv:&quot;)/div[@class=&quot;css-j7qwjs&quot;]/div[@class=&quot;css-0&quot;]/div[@class=&quot;css-0&quot;]/div[@class=&quot;css-3q5yk1&quot;]/div[@class=&quot;css-1g6fs54&quot;]/div[@class=&quot;css-dj8sho&quot;]/div[@class=&quot;react-flow&quot;]/div[@class=&quot;react-flow__renderer&quot;]/div[@class=&quot;react-flow__pane&quot;]/div[@class=&quot;react-flow__viewport react-flow__container&quot;]/div[@class=&quot;react-flow__nodes&quot;]/div[@class=&quot;react-flow__node react-flow__node-custom selectable&quot;]/div[@class=&quot;node-container react-flow-entityType css-0&quot;]/div[@class=&quot;css-ezw9vm&quot;]/div[@class=&quot;schemabuilder inputWrapper css-se2h9a&quot;]/div[@class=&quot;css-95g4uk&quot;]/div[@class=&quot;css-1xuzov8&quot;]/div[@class=&quot;autocomplete-container&quot;]/input[1]</value>
      <webElementGuid>34d807c5-2291-4658-9461-a45a231ad5cf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@value=''])[2]</value>
      <webElementGuid>4f42501b-98bf-4cec-b9cb-fcd92da8476a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='chakra-modal--body-:r2hv:']/div/div[2]/div/div/div[2]/div[2]/div/div/div/div/div[2]/div[30]/div/div/div/div/div/div/input</value>
      <webElementGuid>bdea98b4-d950-4e29-b7eb-e1f094f8f1fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[30]/div/div/div/div/div/div/input</value>
      <webElementGuid>25c9df61-de36-4136-9fbb-f176cf3a8c43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Type here' and @type = 'text']</value>
      <webElementGuid>b35053d6-2b47-46e6-a733-3d6246c8b737</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
