<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Policy Store_chakra-checkbox__control _b414cb</name>
   <tag></tag>
   <elementGuidId>992e03bf-c086-40e4-9566-28e8420e43ba</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='chakra-modal--body-:r67:']/div/div[3]/div/div/div/div/label/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.chakra-checkbox__control.css-1ydjfm6</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>.chakra-checkbox__control >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>785db9ff-c041-438d-81a8-17f93d22d4be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chakra-checkbox__control css-1ydjfm6</value>
      <webElementGuid>b95de1a9-6716-4223-aa8e-b2ebbe16480f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>6ad17254-9af9-4a46-8cfd-c4f62081cbb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;chakra-modal--body-:r67:&quot;)/div[@class=&quot;css-j7qwjs&quot;]/div[@class=&quot;css-dtfnrj&quot;]/div[@class=&quot;chakra-stack css-o5l3sd&quot;]/div[@class=&quot;chakra-stack css-10gncol&quot;]/div[@class=&quot;css-2hv6b6&quot;]/div[@class=&quot;css-1ngurdz&quot;]/label[@class=&quot;chakra-checkbox css-1577qb8&quot;]/span[@class=&quot;chakra-checkbox__control css-1ydjfm6&quot;]</value>
      <webElementGuid>3b03a251-8e34-4e0d-a876-a2aa8c0f1812</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='chakra-modal--body-:r67:']/div/div[3]/div/div/div/div/label/span</value>
      <webElementGuid>e6ad6967-fb03-4839-811f-98811793bec4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/label/span</value>
      <webElementGuid>a2caeacd-4bc2-42fa-97fc-cee88a9d07f2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
