<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_This is for testing the applicati</name>
   <tag></tag>
   <elementGuidId>b7943bac-3c7c-4bcf-bb05-b66ffd6825e4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='description']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#description</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Give your application a description&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>b4f5f72b-192d-407c-8c2f-5260131d94c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>description</value>
      <webElementGuid>f439cbc4-51ae-4f8a-a66d-0cbd0e748863</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Give your application a description</value>
      <webElementGuid>b1ed0ad0-7cc4-4703-9448-8f4990f37915</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>description</value>
      <webElementGuid>bc78fa81-db67-48f1-b3d4-5b034c7a4b12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chakra-textarea css-1hg9r7u</value>
      <webElementGuid>d06122a1-f1dd-42a0-a772-119b4f52d198</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>This is for testing the applicati</value>
      <webElementGuid>4c8322b2-2c16-4a21-bc16-c9fbffadaae6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;description&quot;)</value>
      <webElementGuid>e340cfa9-ea6d-4cc3-8aab-b80d165e349d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='description']</value>
      <webElementGuid>92482416-005f-4e3a-b5b6-bddb8d4697ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='root']/div/div[3]/div[2]/div/div/div/div[2]/div/div[2]/div[2]/div/textarea</value>
      <webElementGuid>7323e10c-26a1-443f-91f1-0e2cb9b0f1de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[4]/following::textarea[1]</value>
      <webElementGuid>4db8815c-991d-4497-8c9e-e76397052f3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='This is for testing the applicati']/parent::*</value>
      <webElementGuid>64db62e1-6b8d-4aa1-b84b-3b7c98fe3c47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>87c50a3b-7496-427e-9c74-fa76f47fa569</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'description' and @placeholder = 'Give your application a description' and @id = 'description' and (text() = 'This is for testing the applicati' or . = 'This is for testing the applicati')]</value>
      <webElementGuid>d55c8140-fb90-43e7-8d31-a2fddcd8b48d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
